version: '3.6'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build:
      context: .
      args:
        - USER
        - UID
    command: >
     bash -c 'rm -f /dog_walking/tmp/pids/* &&
              bundle check ||
              bundle install &&
              bundle exec rails s -p 3000 -b 0.0.0.0'
    volumes:
      - .:/dog_walking
    ports:
      - "3000:3000"
    depends_on:
      - db
