development: &default
  adapter: postgresql
  encoding: unicode
  database: dogwalking_development
  pool: 5
  username: postgres
  password:
  host: db
  port: 5432

test:
  <<: *default
  database: dogwalking_test
